name: ci
on: [ push ]
jobs:
  CI:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up keychain
        run: |
          security create-keychain -p passwd build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p passwd build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k actions build.keychain

      - name: Test
        run: |
          go test -v -short ./...