name: ci
on: [ push ]
env:
  ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH: go1.19
jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: |
          sudo apt update
          sudo apt install libgtk-4-dev
          go test -v ./...