name: ci
on: [ push ]
jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: |
          pass init test
          go test -v ./...